export type ComplianceFramework = {
  slug: string;
  title: string;
  shortTitle: string;
  shortDesc: string;
  iconName: string;
  gradient: string;
  accentColor: string;
  category: string;
  heroDesc: string;
  whoNeedsIt: string[];
  whatWeDo: { title: string; desc: string }[];
  keyRequirements: string[];
  faqs: { q: string; a: string }[];
  benefits: string[];
  relatedServices: { title: string; slug: string }[];
};

export const complianceFrameworks: ComplianceFramework[] = [
  {
    slug: "rbi-framework",
    title: "RBI Cybersecurity Framework",
    shortTitle: "RBI",
    shortDesc: "Master Directions on IT Risk & Cybersecurity for banks, cooperative banks, UCBs and NBFCs.",
    iconName: "FiClipboard",
    gradient: "from-[#2B7BE4] to-[#3B82F6]",
    accentColor: "#2B7BE4",
    category: "Indian Regulations",
    heroDesc: "The Reserve Bank of India's Master Directions on IT Governance, Risk, Controls and Assurance Practices are the most important cybersecurity mandate for any regulated financial entity in India. Non-compliance isn't theoretical risk — RBI is actively imposing penalties on banks found non-compliant. Cybria Secure helps cooperative banks, UCBs and NBFCs achieve and sustain full RBI compliance.",
    whoNeedsIt: ["Scheduled Commercial Banks", "Urban Cooperative Banks (UCBs)", "District Central Cooperative Banks", "State Cooperative Banks", "NBFCs (NBFC-D, NBFC-ND-SI)", "Payment System Operators", "Account Aggregators"],
    whatWeDo: [
      { title: "Gap Assessment", desc: "Benchmark your current state against all RBI Master Direction requirements and produce a prioritized gap report." },
      { title: "Policy & Documentation", desc: "Draft Board-approved Cybersecurity Policy, IT Risk Framework, IRP, BCP — all formatted to satisfy RBI inspection evidence requirements." },
      { title: "VAPT with RBI-Format Report", desc: "Conduct mandatory annual VAPT with manual testing evidence — formatted to meet RBI inspection documentation requirements." },
      { title: "IRP Development & Testing", desc: "Build and tabletop-test your Incident Response Plan — including the mandatory RBI 6-hour notification workflow." },
      { title: "Pre-Inspection Preparation", desc: "Mock inspection walkthrough, evidence compilation and documentation review before your RBI audit." },
      { title: "CISO-as-a-Service", desc: "Fulfill the RBI CISO mandate for cooperative banks and NBFCs without a full-time executive hire." },
    ],
    keyRequirements: [
      "Board-approved Cybersecurity Policy",
      "Designated CISO with defined reporting lines",
      "Annual VAPT for internet-facing systems",
      "Quarterly VAPT for critical systems",
      "Tested Incident Response Plan",
      "6-hour RBI incident notification capability",
      "Business Continuity Plan with verified RTO/RPO",
      "Periodic security awareness training for all staff",
      "Third-party/vendor risk management controls",
      "Patch management and vulnerability management process",
    ],
    faqs: [
      { q: "Does RBI compliance apply to our small cooperative bank?", a: "Yes. RBI Master Directions apply to all regulated entities including urban cooperative banks and district cooperative banks, regardless of size. The requirements scale with the complexity of your IT environment, but the obligation exists for all." },
      { q: "We have an upcoming RBI inspection. How quickly can you help?", a: "Contact us immediately. We can begin a gap assessment within one week and prioritize pre-inspection preparation. The sooner we start, the more we can achieve before the inspection date." },
      { q: "What does the RBI 6-hour notification requirement mean?", a: "RBI mandates that banks notify them within 6 hours of detecting a cyber incident. This requires a pre-built incident reporting process, designated personnel, and a tested IRP — not something you can improvise during an active attack." },
      { q: "Can a vCISO satisfy the RBI CISO appointment requirement?", a: "For most cooperative banks and NBFCs, yes. The RBI requires the CISO function to be fulfilled with defined reporting lines. Our vCISO service meets this requirement for regulated entities that cannot justify a full-time executive." },
    ],
    benefits: ["Pass RBI inspections confidently", "Avoid regulatory penalties and reputational damage", "File cyber incident notifications on time", "Board-ready compliance documentation", "Ongoing compliance maintenance support"],
    relatedServices: [
      { title: "RBI Cybersecurity Service", slug: "rbi-compliance" },
      { title: "VAPT for Banks", slug: "web-application-vapt" },
      { title: "Virtual CISO (vCISO)", slug: "vciso" },
      { title: "Incident Response", slug: "incident-response" },
    ],
  },
  {
    slug: "iso-27001",
    title: "ISO 27001:2022",
    shortTitle: "ISO 27001",
    shortDesc: "Global gold standard for Information Security Management Systems — required by enterprise clients worldwide.",
    iconName: "FiShield",
    gradient: "from-[#10B981] to-[#059669]",
    accentColor: "#10B981",
    category: "International Standards",
    heroDesc: "ISO 27001:2022 is the internationally recognized standard for information security management. Enterprise clients, MNCs and global procurement teams now mandate ISO 27001 certification from their Indian vendors and service providers. Cybria Secure guides you from gap assessment through to certification — with an ISMS that actually protects your business, not just a paper exercise.",
    whoNeedsIt: ["IT and software companies", "SaaS and cloud service providers", "BPO and KPO companies", "Financial services firms", "Healthcare organizations", "Any company handling client data", "Organizations pursuing global enterprise contracts"],
    whatWeDo: [
      { title: "Gap Assessment", desc: "Benchmark against all ISO 27001:2022 clauses and Annex A controls with effort estimates and project timeline." },
      { title: "Risk Assessment (ISO 27005)", desc: "Asset-based risk assessment methodology, risk register development and risk treatment plan." },
      { title: "ISMS Documentation", desc: "All required policies, procedures, Statement of Applicability (SoA), risk treatment plan and supporting records." },
      { title: "Controls Implementation", desc: "Support implementing all applicable Annex A technical and organizational controls." },
      { title: "Internal Audit", desc: "Conduct the mandatory internal audit to identify non-conformities before the certification audit." },
      { title: "Certification Audit Support", desc: "Accompany you during Stage 1 and Stage 2 audits with an accredited certification body — and address any non-conformities." },
    ],
    keyRequirements: [
      "Information Security Policy",
      "ISMS scope definition",
      "Risk assessment and treatment process",
      "Statement of Applicability (SoA)",
      "Annex A controls implementation (93 controls in 2022 version)",
      "Supplier security requirements",
      "Incident management procedure",
      "Internal audit program",
      "Management review",
      "Continual improvement process",
    ],
    faqs: [
      { q: "How long does ISO 27001 certification take?", a: "Typically 3–6 months for a first-time implementation depending on organization size and current security maturity. We provide a realistic project plan after the initial gap assessment." },
      { q: "What changed in ISO 27001:2022 vs 2013?", a: "The 2022 version restructured Annex A from 114 to 93 controls across 4 themes, and added 11 new controls covering cloud security, threat intelligence, web filtering, data masking and secure coding. Organizations certified to the 2013 version must transition by October 2025." },
      { q: "We keep losing enterprise deals because we don't have ISO 27001. How fast can you get us certified?", a: "3–4 months is achievable for a focused mid-sized organization with management commitment. Contact us — we'll assess your current state and give you a realistic timeline after a 1-hour scoping call." },
      { q: "Do you help select the certification body?", a: "Yes. We work with multiple UKAS and DAkkS accredited certification bodies and help you select the right one for your size, industry and budget." },
    ],
    benefits: ["Win enterprise clients and pass security questionnaires", "Globally recognized security signal", "Structured risk management framework", "Simplify RBI and other regulatory compliance", "Competitive differentiator in Indian IT sector"],
    relatedServices: [
      { title: "ISO 27001 Implementation", slug: "iso-27001" },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
      { title: "Virtual CISO", slug: "vciso" },
      { title: "VAPT", slug: "web-application-vapt" },
    ],
  },
  {
    slug: "soc2",
    title: "SOC 2 Type II",
    shortTitle: "SOC 2",
    shortDesc: "Trust services criteria audit for security, availability and confidentiality — required by US and global enterprise clients.",
    iconName: "FiBarChart2",
    gradient: "from-[#7C3AED] to-[#8B5CF6]",
    accentColor: "#7C3AED",
    category: "International Standards",
    heroDesc: "SOC 2 Type II is the trust standard for technology companies serving North American and global enterprise clients. If your SaaS platform, IT services company or data processor is losing deals because US clients ask for a SOC 2 report — Cybria Secure helps you achieve and maintain SOC 2 compliance with minimal business disruption.",
    whoNeedsIt: ["SaaS companies with US/global clients", "Cloud service providers", "Data centers and hosting providers", "Managed service providers (MSPs)", "Healthcare IT companies", "Fintech companies serving international markets"],
    whatWeDo: [
      { title: "Readiness Assessment", desc: "Gap assessment against SOC 2 Trust Services Criteria for Security, Availability, Confidentiality, Processing Integrity and/or Privacy." },
      { title: "Control Design & Implementation", desc: "Design and implement the required controls across people, process and technology." },
      { title: "Policy Development", desc: "Develop all required policies and procedures aligned with the selected Trust Services Criteria." },
      { title: "Evidence Collection", desc: "Build evidence collection processes and documentation for the audit period." },
      { title: "Auditor Liaison", desc: "Work with your selected CPA firm during the Type II audit period and address any observations." },
      { title: "Continuous Monitoring", desc: "Ongoing control monitoring to maintain SOC 2 compliance between annual audits." },
    ],
    keyRequirements: [
      "Security (CC series) controls — mandatory",
      "Logical and physical access controls",
      "System operations and change management",
      "Risk mitigation and monitoring",
      "Vendor management controls",
      "Incident response procedures",
      "Encryption and key management",
      "Vulnerability management program",
      "Background checks and HR security",
      "Business continuity and disaster recovery",
    ],
    faqs: [
      { q: "What's the difference between SOC 2 Type I and Type II?", a: "Type I assesses whether controls are suitably designed at a point in time. Type II assesses whether those controls operated effectively over a period (minimum 6 months). Enterprise clients almost always require Type II." },
      { q: "Do we need all 5 Trust Services Criteria?", a: "No. Security (Common Criteria) is mandatory. Availability, Confidentiality, Processing Integrity and Privacy are selected based on what's relevant to your service commitments. Most SaaS companies include Security + Availability + Confidentiality." },
      { q: "How long does SOC 2 Type II take?", a: "Preparation: 3–6 months. Observation period: 6–12 months. Total: 9–18 months for your first report. We help you compress the preparation phase without cutting corners." },
    ],
    benefits: ["Open doors with US and global enterprise clients", "Differentiate from competitors without SOC 2", "Demonstrate operational security rigor", "Reduce client security questionnaire burden", "Foundation for ISO 27001 and other frameworks"],
    relatedServices: [
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
      { title: "ISO 27001 Implementation", slug: "iso-27001" },
      { title: "Virtual CISO", slug: "vciso" },
      { title: "Cloud Security Assessment", slug: "cloud-security-assessment" },
    ],
  },
  {
    slug: "pci-dss",
    title: "PCI-DSS 4.0",
    shortTitle: "PCI-DSS",
    shortDesc: "Payment Card Industry Data Security Standard — mandatory for any business storing, processing or transmitting cardholder data.",
    iconName: "FiCreditCard",
    gradient: "from-[#FF5CA8] to-[#EC4899]",
    accentColor: "#FF5CA8",
    category: "International Standards",
    heroDesc: "PCI-DSS applies to every business that accepts, processes, stores or transmits payment card data. Version 4.0, effective April 2024, introduced significant changes — new authentication requirements, expanded scope for e-commerce, and stronger encryption mandates. Cybria Secure provides PCI-DSS gap assessment, remediation and QSA-ready documentation for Indian payment businesses.",
    whoNeedsIt: ["E-commerce platforms accepting card payments", "Payment aggregators and payment gateways", "Banks and NBFCs processing card transactions", "Retail businesses with POS systems", "Hotels, airlines and travel companies", "Healthcare organizations accepting card payments"],
    whatWeDo: [
      { title: "Scope Definition", desc: "Define the cardholder data environment (CDE) and identify all systems, networks and processes in scope." },
      { title: "Gap Assessment", desc: "Benchmark against all 12 PCI-DSS 4.0 requirements and produce a prioritized remediation plan." },
      { title: "Network Segmentation Review", desc: "Validate network segmentation isolating the CDE from out-of-scope systems." },
      { title: "VAPT (ASV Scans)", desc: "Quarterly ASV vulnerability scans and annual penetration testing as required by PCI-DSS." },
      { title: "Policy & Documentation", desc: "Develop all required policies, procedures, and evidence documentation for QSA assessment." },
      { title: "QSA Audit Support", desc: "Support during the formal QSA assessment and help remediate any findings before certification." },
    ],
    keyRequirements: [
      "Network segmentation and firewall rules (Req 1)",
      "No default vendor passwords (Req 2)",
      "Protect stored cardholder data (Req 3)",
      "Encrypt transmission of cardholder data (Req 4)",
      "Protect systems against malware (Req 5)",
      "Develop and maintain secure systems (Req 6)",
      "Restrict access to cardholder data (Req 7)",
      "Identify and authenticate access (Req 8 — new MFA requirements in v4.0)",
      "Restrict physical access (Req 9)",
      "Log, monitor, and test all networks (Req 10–11)",
      "Maintain an information security policy (Req 12)",
    ],
    faqs: [
      { q: "Do Indian e-commerce companies need PCI-DSS?", a: "Yes. If you process, store or transmit cardholder data — or if your platform connects to payment gateways — PCI-DSS applies regardless of geography. The card brands (Visa, Mastercard) mandate it globally." },
      { q: "What changed in PCI-DSS version 4.0?", a: "Key changes include mandatory MFA for all CDE access, stronger password requirements, expanded scope for e-commerce and phishing controls, new targeted risk analysis approach, and several new requirements becoming mandatory in April 2025." },
      { q: "We use a payment gateway — are we still in scope?", a: "Possibly, depending on your integration. Using an iframe or redirect significantly reduces scope. We assess your specific payment flow to determine your actual CDE scope before any remediation work begins." },
    ],
    benefits: ["Mandatory for card payment acceptance", "Prevent cardholder data breaches and fines", "Meet RBI Payment Aggregator guidelines", "Build customer trust in payment security", "Avoid card brand penalties for non-compliance"],
    relatedServices: [
      { title: "Web Application VAPT", slug: "web-application-vapt" },
      { title: "API Security Testing", slug: "api-security-testing" },
      { title: "Network Security Audit", slug: "network-security-audit" },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
    ],
  },
  {
    slug: "dpdpa",
    title: "DPDPA 2023 (India)",
    shortTitle: "DPDPA",
    shortDesc: "India's Digital Personal Data Protection Act 2023 — compliance for all organizations processing personal data of Indian residents.",
    iconName: "FiLock",
    gradient: "from-[#F59E0B] to-[#EF4444]",
    accentColor: "#F59E0B",
    category: "Indian Regulations",
    heroDesc: "India's Digital Personal Data Protection Act 2023 (DPDPA) is a landmark law governing the processing of personal data of individuals in India. Any organization — Indian or foreign — that processes personal data of Indian residents must comply. With significant penalties for data breaches and non-compliance, DPDPA is a business-critical obligation. Cybria Secure helps organizations understand, implement and maintain DPDPA compliance.",
    whoNeedsIt: ["Every Indian company processing customer data", "Foreign companies processing Indian resident data", "Healthcare organizations holding patient data", "E-commerce platforms with Indian customers", "Banks and financial institutions", "HR and payroll systems handling employee data", "Schools and educational institutions"],
    whatWeDo: [
      { title: "Data Mapping & Inventory", desc: "Identify all personal data, where it's stored, how it flows, who processes it and for what purpose." },
      { title: "Gap Assessment", desc: "Benchmark current practices against DPDPA requirements — consent management, data minimization, breach notification." },
      { title: "Privacy Policy & Notice", desc: "Draft compliant privacy notices, consent management workflows and data subject rights procedures." },
      { title: "Technical Controls", desc: "Implement data protection controls — encryption, access controls, data retention and deletion mechanisms." },
      { title: "Breach Response", desc: "Build breach detection and mandatory notification procedures aligned with DPDPA timelines." },
      { title: "Ongoing Compliance", desc: "Data Protection Officer advisory, periodic review and staff training on DPDPA obligations." },
    ],
    keyRequirements: [
      "Lawful basis for processing (consent, legitimate use)",
      "Clear and accessible consent mechanism",
      "Data minimization — collect only what's needed",
      "Purpose limitation — use data only as specified",
      "Data accuracy and quality obligations",
      "Storage limitation — delete data when purpose ends",
      "Breach notification to Data Protection Board",
      "Data subject rights — access, correction, erasure",
      "Children's data protection (parental consent for minors)",
      "Significant data fiduciary additional obligations",
    ],
    faqs: [
      { q: "When does DPDPA 2023 come into force?", a: "The Act received Presidential assent in August 2023. The central government will notify the effective date via Rules — organizations should begin compliance preparation now as Rules are expected to be finalized soon." },
      { q: "What are the penalties under DPDPA?", a: "Penalties up to ₹250 crore per violation for data breaches, failure to notify the Data Protection Board, or non-fulfilment of obligations regarding children's data. Significant data fiduciaries face higher penalties." },
      { q: "Is DPDPA similar to GDPR?", a: "DPDPA shares principles with GDPR — consent, purpose limitation, data minimization, breach notification, data subject rights. However, DPDPA is specifically tailored to the Indian context with some differences in scope, rights and enforcement." },
      { q: "We already have ISO 27001. Are we DPDPA compliant?", a: "Not automatically. ISO 27001 covers information security broadly. DPDPA adds specific requirements around consent management, data subject rights, breach notification timelines and children's data that ISO 27001 doesn't mandate. A dedicated DPDPA gap assessment is needed." },
    ],
    benefits: ["Avoid significant DPDPA penalties", "Build customer trust through data transparency", "Foundation for GDPR compliance if expanding to EU", "Competitive advantage — early compliance signals maturity", "Structured data governance framework"],
    relatedServices: [
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
      { title: "ISO 27001 Implementation", slug: "iso-27001" },
      { title: "Virtual CISO", slug: "vciso" },
      { title: "Security Awareness Training", slug: "security-awareness-training" },
    ],
  },
  {
    slug: "hipaa",
    title: "HIPAA",
    shortTitle: "HIPAA",
    shortDesc: "Health Insurance Portability and Accountability Act — mandatory for healthcare organizations and their technology vendors serving US markets.",
    iconName: "FiHeart",
    gradient: "from-[#FF5CA8] to-[#7C3AED]",
    accentColor: "#FF5CA8",
    category: "International Standards",
    heroDesc: "HIPAA applies to covered entities and business associates handling Protected Health Information (PHI) — including Indian healthcare IT companies, telemedicine platforms and health-tech vendors serving US clients. HIPAA violations carry severe penalties. Cybria Secure provides HIPAA gap assessments and security controls implementation for healthcare and health-tech organizations.",
    whoNeedsIt: ["Hospitals and clinics serving US patients", "Health-tech companies with US clients", "Telemedicine platforms", "Healthcare IT vendors and developers", "Health insurance companies", "Billing and coding services handling PHI", "Indian IT companies building US healthcare software"],
    whatWeDo: [
      { title: "HIPAA Risk Assessment", desc: "Mandatory HIPAA Security Rule risk analysis — identify where PHI exists and all threats to its confidentiality, integrity and availability." },
      { title: "Gap Assessment", desc: "Benchmark against HIPAA Administrative, Physical and Technical Safeguards." },
      { title: "Policy Development", desc: "HIPAA-required policies, procedures and workforce training documentation." },
      { title: "Technical Safeguards", desc: "Implement access controls, audit controls, integrity controls and transmission security for PHI." },
      { title: "Business Associate Agreement (BAA) Review", desc: "Review and advise on BAA requirements for vendors handling PHI on your behalf." },
      { title: "Breach Response", desc: "HIPAA breach notification procedures — including 60-day reporting requirement to HHS." },
    ],
    keyRequirements: [
      "Risk analysis and risk management (mandatory)",
      "Workforce training and management",
      "Contingency and disaster recovery planning",
      "Access controls and unique user identification",
      "Audit controls and activity logging",
      "Integrity controls for PHI",
      "Encryption for PHI in transit and at rest",
      "Physical safeguards for workstations and devices",
      "Business Associate Agreements (BAAs)",
      "Breach notification within 60 days",
    ],
    faqs: [
      { q: "Does HIPAA apply to Indian healthcare companies?", a: "HIPAA applies if you handle Protected Health Information of US individuals — regardless of your geography. Indian health-tech companies building US healthcare software or serving US healthcare clients are typically covered." },
      { q: "What are HIPAA penalties?", a: "Civil penalties range from $100 to $50,000 per violation, up to $1.9M per violation category per year. Criminal penalties include fines and imprisonment for willful neglect. India-based companies serving US clients face the same penalties." },
    ],
    benefits: ["Enable US healthcare market access", "Protect patient data and institutional reputation", "Avoid significant civil and criminal penalties", "Required for US healthcare client contracts", "Foundation for broader healthcare compliance"],
    relatedServices: [
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
      { title: "Network Security Audit", slug: "network-security-audit" },
      { title: "Web Application VAPT", slug: "web-application-vapt" },
      { title: "Security Awareness Training", slug: "security-awareness-training" },
    ],
  },
  {
    slug: "nist-csf",
    title: "NIST Cybersecurity Framework",
    shortTitle: "NIST CSF",
    shortDesc: "NIST CSF 2.0 implementation and maturity assessment — the global voluntary framework for managing cybersecurity risk.",
    iconName: "FiBarChart2",
    gradient: "from-[#2B7BE4] to-[#7C3AED]",
    accentColor: "#5B6EF7",
    category: "International Standards",
    heroDesc: "The NIST Cybersecurity Framework (CSF) 2.0 is the most widely adopted voluntary cybersecurity framework globally — used by organizations from SMEs to multinationals to structure their security programs. NIST CSF provides a common language for cybersecurity risk management across Govern, Identify, Protect, Detect, Respond and Recover functions. Cybria Secure implements NIST CSF to build structured, measurable security programs.",
    whoNeedsIt: ["Organizations seeking a structured security program", "Companies working with US government contractors", "Critical infrastructure operators", "Organizations pursuing cybersecurity maturity improvement", "Companies wanting a framework beyond compliance checklists", "Technology vendors and managed service providers"],
    whatWeDo: [
      { title: "Current State Assessment", desc: "Evaluate your organization's current cybersecurity posture across all 6 NIST CSF 2.0 functions." },
      { title: "Target Profile Development", desc: "Define your target security posture based on risk appetite, business objectives and regulatory obligations." },
      { title: "Gap Analysis", desc: "Identify gaps between current and target profile with effort estimates and priority ranking." },
      { title: "Roadmap Development", desc: "Build a phased implementation roadmap with measurable milestones." },
      { title: "Controls Implementation", desc: "Implement priority controls across all NIST CSF functions." },
      { title: "Maturity Measurement", desc: "Ongoing maturity measurement and improvement tracking against your target profile." },
    ],
    keyRequirements: [
      "GOVERN — Cybersecurity risk strategy and policy",
      "IDENTIFY — Asset management and risk assessment",
      "PROTECT — Access control, awareness, data security",
      "DETECT — Continuous monitoring and anomaly detection",
      "RESPOND — Incident response and communication",
      "RECOVER — Recovery planning and improvements",
    ],
    faqs: [
      { q: "Is NIST CSF mandatory?", a: "NIST CSF is voluntary in most contexts. However, it is required for US federal contractors and increasingly referenced in regulations worldwide. Its real value is as a comprehensive framework for building a mature, measurable security program." },
      { q: "How does NIST CSF 2.0 differ from 1.1?", a: "CSF 2.0 (released February 2024) added a sixth function — GOVERN — which addresses organizational cybersecurity leadership, strategy and supply chain risk management. It also expanded applicability beyond critical infrastructure to all organizations." },
    ],
    benefits: ["Structured, measurable security program", "Common language for Board-level risk communication", "Applicable to any organization size or sector", "Aligns with ISO 27001, SOC 2 and other frameworks", "Foundation for continuous security improvement"],
    relatedServices: [
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
      { title: "Virtual CISO", slug: "vciso" },
      { title: "ISO 27001 Implementation", slug: "iso-27001" },
      { title: "Network Security Audit", slug: "network-security-audit" },
    ],
  },
  {
    slug: "iec62443",
    title: "IEC 62443 (OT Security)",
    shortTitle: "IEC 62443",
    shortDesc: "Industrial cybersecurity standard for OT/ICS environments — manufacturing, energy and critical infrastructure.",
    iconName: "FiCpu",
    gradient: "from-[#F59E0B] to-[#EF4444]",
    accentColor: "#F59E0B",
    category: "Industry Standards",
    heroDesc: "IEC 62443 is the international standard for securing Industrial Automation and Control Systems (IACS). As OT systems connect to IT networks and the internet, the attack surface of Indian manufacturers, energy utilities and critical infrastructure operators has expanded dramatically. IEC 62443 provides the framework for securing these environments. Cybria Secure delivers IEC 62443 aligned OT security assessments without disrupting production.",
    whoNeedsIt: ["Manufacturing companies with SCADA/PLC", "Energy and utility operators", "Oil and gas companies", "Water treatment facilities", "Pharmaceutical manufacturers (21 CFR Part 11)", "OT vendors and system integrators", "Critical infrastructure operators"],
    whatWeDo: [
      { title: "OT Asset Discovery", desc: "Non-intrusive passive discovery of all OT assets — PLCs, RTUs, HMIs, historians and engineering workstations." },
      { title: "Zone and Conduit Design", desc: "Define security zones and conduits following IEC 62443-3-2 methodology." },
      { title: "Risk Assessment", desc: "OT-specific risk assessment against IEC 62443 Security Level targets." },
      { title: "Gap Assessment", desc: "Benchmark current OT controls against IEC 62443-3-3 System Security Requirements." },
      { title: "Remediation Roadmap", desc: "Prioritized remediation plan with OT-specific constraints — maintenance windows, vendor dependencies." },
      { title: "Ongoing Support", desc: "Periodic re-assessment and support for IEC 62443 certification engagement." },
    ],
    keyRequirements: [
      "Security zone and conduit model (IEC 62443-3-2)",
      "OT asset inventory and classification",
      "Access control for OT systems",
      "Remote access security",
      "Patch management for OT components",
      "OT-specific incident response",
      "Backup and recovery for OT systems",
      "Physical security for OT environments",
      "Network segmentation between IT and OT",
      "Supply chain and vendor security",
    ],
    faqs: [
      { q: "Is IEC 62443 mandatory in India?", a: "Not universally mandatory yet, but CEA guidelines for power sector OT security reference IEC 62443. Additionally, global manufacturing clients and insurers are increasingly requiring IEC 62443 alignment as a condition of contracts and cyber insurance." },
      { q: "Can you assess our OT environment without shutting down production?", a: "Yes. Our OT assessment uses passive discovery and architecture review techniques for live production systems. Active penetration testing is only conducted on isolated systems or during scheduled maintenance windows — never on live PLCs or RTUs." },
    ],
    benefits: ["Secure OT/IT convergence safely", "Meet global customer and insurance requirements", "Prevent production-disrupting cyberattacks", "Structured OT security governance", "Align with international critical infrastructure standards"],
    relatedServices: [
      { title: "OT / SCADA Security", slug: "ot-scada-security" },
      { title: "Network Security Audit", slug: "network-security-audit" },
      { title: "Incident Response", slug: "incident-response" },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment" },
    ],
  },
];

export const getComplianceBySlug = (slug: string) =>
  complianceFrameworks.find((f) => f.slug === slug);