export type Industry = {
  slug: string;
  title: string;
  shortDesc: string;
  iconName: string;
  gradient: string;
  accentColor: string;
  heroDesc: string;
  threats: string[];
  services: { title: string; slug: string; desc: string }[];
  regulations: string[];
  faqs: { q: string; a: string }[];
  stats: { value: string; label: string }[];
};

export const industries: Industry[] = [
  {
    slug: "bfsi",
    title: "Banking, Financial Services & Insurance (BFSI)",
    shortDesc: "Cybersecurity for banks, cooperative banks, NBFCs, insurance companies and fintech firms — RBI, SEBI and IRDAI compliance.",
    iconName: "FiCreditCard",
    gradient: "from-[#2B7BE4] to-[#3B82F6]",
    accentColor: "#2B7BE4",
    heroDesc: "The BFSI sector is the most targeted industry for cyberattacks in India. From cooperative banks in Tier-2 cities to NBFCs and insurance companies, every financial institution is in the crosshairs. Cybria Secure brings deep BFSI expertise — mandatory RBI compliance, VAPT for core banking systems, and 24/7 incident response.",
    threats: [
      "Ransomware targeting Core Banking Solution (CBS) servers",
      "Phishing attacks on bank staff and customers",
      "ATM and card skimming attacks",
      "API vulnerabilities in mobile banking apps",
      "Insider fraud and privilege misuse",
      "Third-party CBS vendor access exploitation",
      "Business Email Compromise (BEC) targeting finance teams",
      "DDoS attacks on internet banking portals",
    ],
    services: [
      { title: "RBI Cybersecurity Compliance", slug: "rbi-compliance", desc: "End-to-end compliance with RBI Master Directions on IT Risk & Cybersecurity Framework." },
      { title: "VAPT for CBS & Internet Banking", slug: "web-application-vapt", desc: "Manual penetration testing of Core Banking Solutions, mobile banking apps and payment APIs." },
      { title: "Incident Response", slug: "incident-response", desc: "24/7 response with RBI 6-hour notification support and forensic investigation." },
      { title: "Security Awareness Training", slug: "security-awareness-training", desc: "Staff training in Marathi, Hindi and English — phishing simulation and branch security culture." },
      { title: "Virtual CISO (vCISO)", slug: "vciso", desc: "Fulfill the RBI CISO mandate without a full-time hire." },
    ],
    regulations: ["RBI Master Directions on IT Risk", "SEBI Cybersecurity Circular", "IRDAI Information & Cybersecurity Guidelines", "PCI-DSS", "CERT-In Directions 2022"],
    faqs: [
      { q: "What does RBI require for cooperative banks?", a: "Board-approved Cybersecurity Policy, CISO appointment, annual VAPT, tested IRP, BCP/DR with verified RTO/RPO, and periodic staff security training." },
      { q: "How soon must cyber incidents be reported to RBI?", a: "Within 6 hours of detection. Cybria Secure supports you with notification drafting, evidence packaging and liaison with RBI during the incident." },
      { q: "Do you work with small cooperative banks in Maharashtra?", a: "Yes. We specialize in cooperative banks in Kolhapur, Sangli, Solapur and across Maharashtra — with on-site support and Marathi-language training." },
    ],
    stats: [{ value: "6 hrs", label: "RBI Incident Notification Window" }, { value: "100%", label: "RBI Audit Pass Rate" }, { value: "50+", label: "Banks Served" }, { value: "24/7", label: "Incident Response" }],
  },
  {
    slug: "healthcare",
    title: "Healthcare & Pharmaceuticals",
    shortDesc: "HIPAA, NABH and patient data protection for hospitals, diagnostic labs, health-tech and pharma companies.",
    iconName: "FiHeart",
    gradient: "from-[#FF5CA8] to-[#EC4899]",
    accentColor: "#FF5CA8",
    heroDesc: "Healthcare organizations hold the most sensitive personal data — patient records, diagnostic information, prescriptions. Breaches in healthcare cause direct harm to patients and destroy institutional trust. Cybria Secure protects hospital networks, medical devices, and patient portals from ransomware and unauthorized access.",
    threats: [
      "Ransomware encrypting hospital management systems",
      "Patient data theft and dark web sale",
      "Medical device security vulnerabilities",
      "Insecure patient portals and health apps",
      "Third-party lab and diagnostic system access",
      "Insider data exfiltration by hospital staff",
      "Phishing targeting doctors and administrative staff",
      "Supply chain attacks on pharma ERP systems",
    ],
    services: [
      { title: "Network Security Audit", slug: "network-security-audit", desc: "Secure hospital networks, medical device connections and nurse station endpoints." },
      { title: "Web Application VAPT", slug: "web-application-vapt", desc: "Patient portals, appointment systems and health-tech app security testing." },
      { title: "Incident Response", slug: "incident-response", desc: "Ransomware recovery for healthcare with minimal patient care disruption." },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment", desc: "HIPAA alignment, NABH IT standards and health data governance framework." },
    ],
    regulations: ["DPDPA 2023 (India)", "HIPAA", "NABH IT Standards", "CERT-In Directions 2022"],
    faqs: [
      { q: "Is HIPAA compliance required in India?", a: "HIPAA applies to US-connected operations. For Indian healthcare, DPDPA 2023 and NABH IT standards are the primary requirements. We cover all applicable frameworks." },
      { q: "How do you handle medical device security?", a: "We perform non-intrusive assessment of medical device network connections, manufacturer security documentation review, and network segmentation recommendations." },
    ],
    stats: [{ value: "DPDPA", label: "Patient Data Compliance" }, { value: "48 hrs", label: "Ransomware Recovery SLA" }, { value: "Zero", label: "Patient Care Disruption Goal" }, { value: "24/7", label: "Incident Response" }],
  },
  {
    slug: "manufacturing",
    title: "Manufacturing & Industrial",
    shortDesc: "OT/IT cybersecurity for foundry, textile, auto and engineering manufacturers — SCADA, PLC and IEC 62443 compliance.",
    iconName: "FiSettings",
    gradient: "from-[#F59E0B] to-[#EF4444]",
    accentColor: "#F59E0B",
    heroDesc: "Kolhapur and Western Maharashtra are home to thousands of foundries, engineering companies, textile manufacturers and auto-ancillary units — many of which now connect SCADA and PLC systems to the internet. This OT/IT convergence creates devastating attack paths. Cybria Secure provides production-safe OT security assessment without disrupting your shop floor.",
    threats: [
      "Ransomware encrypting production systems and ERP",
      "Unauthenticated access to SCADA/HMI from corporate network",
      "Default credentials on PLCs and RTUs",
      "Vendor remote access exploitation",
      "Theft of product designs and R&D IP",
      "Supply chain software attacks on ERP systems",
      "Phishing targeting purchase and finance teams",
      "Industrial espionage via OT network reconnaissance",
    ],
    services: [
      { title: "OT / SCADA Security", slug: "ot-scada-security", desc: "Non-intrusive OT assessment — PLC, SCADA, HMI and OT/IT network segmentation." },
      { title: "Network Security Audit", slug: "network-security-audit", desc: "Corporate IT network penetration testing and segmentation review." },
      { title: "Incident Response", slug: "incident-response", desc: "Ransomware recovery for manufacturing with minimal production downtime." },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment", desc: "IEC 62443 alignment and OT security governance framework." },
    ],
    regulations: ["IEC 62443", "CERT-In Directions 2022", "ISO 27001", "DPDPA 2023"],
    faqs: [
      { q: "Will the OT assessment disrupt our production line?", a: "No. We use passive, non-intrusive techniques for all OT systems. Active testing is only on IT systems and requires explicit agreement. We never probe PLCs or RTUs actively." },
      { q: "Do you serve Kolhapur-based manufacturers?", a: "Yes. Cybria Secure is headquartered in Kolhapur and has direct on-site experience with local foundries, engineering companies and textile manufacturers." },
    ],
    stats: [{ value: "Zero", label: "Production Disruption in Assessments" }, { value: "IEC 62443", label: "OT Security Standard" }, { value: "On-site", label: "Available in Kolhapur" }, { value: "OT+IT", label: "Converged Assessment" }],
  },
  {
    slug: "government",
    title: "Government & Public Sector",
    shortDesc: "Cybersecurity for PSUs, municipalities, government agencies and critical infrastructure — CERT-In compliance.",
    iconName: "FiFlag",
    gradient: "from-[#7C3AED] to-[#8B5CF6]",
    accentColor: "#7C3AED",
    heroDesc: "Government and public sector organizations manage citizen data, critical infrastructure and national security assets at scale. The threat landscape is uniquely severe — from state-sponsored APTs to ransomware targeting municipal systems. Cybria Secure provides CERT-In aligned security assessments and compliance frameworks for government entities.",
    threats: [
      "State-sponsored APT attacks on critical infrastructure",
      "Ransomware targeting municipal and government systems",
      "Citizen data theft from e-governance portals",
      "Insider threats with privileged access to sensitive data",
      "DDoS attacks on government websites and services",
      "Supply chain attacks on government IT vendors",
      "Phishing targeting government employees",
      "Legacy system exploitation",
    ],
    services: [
      { title: "VAPT for Government Portals", slug: "web-application-vapt", desc: "Security testing for e-governance portals, citizen-facing apps and government APIs." },
      { title: "Network Security Audit", slug: "network-security-audit", desc: "Government LAN/WAN security, segmentation and remote access review." },
      { title: "Red Team Operations", slug: "red-teaming", desc: "Adversarial simulation aligned with APT TTPs targeting government organizations." },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment", desc: "CERT-In compliance, IT Act alignment and information security governance." },
    ],
    regulations: ["CERT-In Directions 2022", "IT Act 2000 & Amendments", "NIC Security Policy", "DPDPA 2023", "ISO 27001"],
    faqs: [
      { q: "Are you empanelled with CERT-In?", a: "We follow CERT-In guidelines and directions for all engagements. Our reports are formatted to satisfy CERT-In audit requirements." },
      { q: "Can you help with the mandatory CERT-In incident reporting?", a: "Yes. CERT-In mandates incident reporting within 6 hours. We support government organizations with notification drafting and compliance." },
    ],
    stats: [{ value: "CERT-In", label: "Aligned Assessments" }, { value: "6 hrs", label: "Incident Reporting SLA" }, { value: "APT", label: "Threat Simulation Expertise" }, { value: "24/7", label: "Incident Response" }],
  },
  {
    slug: "retail",
    title: "Retail & E-Commerce",
    shortDesc: "Cybersecurity for retail chains, e-commerce platforms and payment companies — PCI-DSS, DPDPA and API security.",
    iconName: "FiShoppingCart",
    gradient: "from-[#10B981] to-[#059669]",
    accentColor: "#10B981",
    heroDesc: "Retail and e-commerce businesses are high-value targets — customer payment data, PII, and high-volume transaction systems attract constant attacks. From checkout API vulnerabilities to loyalty program fraud, Cybria Secure provides comprehensive security testing and PCI-DSS compliance for Indian retail businesses.",
    threats: [
      "Payment card data theft via web skimming (Magecart)",
      "E-commerce platform API vulnerabilities",
      "Loyalty program fraud and account takeover",
      "Insider data theft by customer support staff",
      "DDoS attacks during sale events",
      "Supply chain attacks on third-party plugins",
      "Customer PII exfiltration",
      "Mobile commerce app vulnerabilities",
    ],
    services: [
      { title: "Web Application VAPT", slug: "web-application-vapt", desc: "E-commerce platform, payment gateway and checkout flow security testing." },
      { title: "API Security Testing", slug: "api-security-testing", desc: "Payment APIs, loyalty program APIs and product catalog API security testing." },
      { title: "Mobile App Security", slug: "mobile-app-security", desc: "iOS and Android retail app security — payment flows, authentication, data storage." },
      { title: "GRC & PCI-DSS", slug: "governance-risk-assessment", desc: "PCI-DSS 4.0 compliance and DPDPA customer data protection framework." },
    ],
    regulations: ["PCI-DSS 4.0", "DPDPA 2023", "RBI Payment Aggregator Guidelines", "CERT-In Directions 2022"],
    faqs: [
      { q: "Is PCI-DSS required for Indian e-commerce companies?", a: "Yes, if you process, store or transmit cardholder data. PCI-DSS applies to any business accepting card payments — including Indian e-commerce platforms and payment aggregators." },
      { q: "How do you test during peak sale periods?", a: "We perform all active testing during agreed off-peak windows. We can also do read-only security assessment during peak periods to avoid any risk to live transactions." },
    ],
    stats: [{ value: "PCI-DSS", label: "Payment Compliance" }, { value: "API", label: "Security Specialization" }, { value: "Zero", label: "Transaction Disruption Goal" }, { value: "DPDPA", label: "Customer Data Protection" }],
  },
  {
    slug: "technology",
    title: "Technology & IT Companies",
    shortDesc: "VAPT, secure SDLC and compliance for SaaS, IT services, startups and software companies targeting global clients.",
    iconName: "FiMonitor",
    gradient: "from-[#2B7BE4] to-[#7C3AED]",
    accentColor: "#5B6EF7",
    heroDesc: "IT and technology companies face a dual challenge — securing their own infrastructure while providing security assurances to their enterprise clients. ISO 27001, SOC 2 and client security questionnaires are now table stakes for Indian IT companies pursuing global accounts. Cybria Secure helps technology companies build security from the inside out.",
    threats: [
      "Source code theft via version control system breaches",
      "Cloud misconfiguration exposing customer data",
      "API vulnerabilities in SaaS platforms",
      "Supply chain attacks through open-source dependencies",
      "Ransomware targeting development environments",
      "Insider developer threat — data exfiltration",
      "Client data exposure through multi-tenant vulnerabilities",
      "Security questionnaire failures losing enterprise deals",
    ],
    services: [
      { title: "Cloud Security Assessment", slug: "cloud-security-assessment", desc: "AWS, Azure, GCP configuration review — IAM, storage, network and multi-tenant isolation." },
      { title: "Web Application VAPT", slug: "web-application-vapt", desc: "SaaS platform, admin portal and customer-facing application security testing." },
      { title: "ISO 27001 Implementation", slug: "iso-27001", desc: "ISMS certification to win enterprise clients and pass security questionnaires." },
      { title: "API Security Testing", slug: "api-security-testing", desc: "REST and GraphQL API testing for SaaS platforms and microservices." },
      { title: "Virtual CISO (vCISO)", slug: "vciso", desc: "Strategic security leadership for tech companies without a full-time security head." },
    ],
    regulations: ["ISO 27001:2022", "SOC 2 Type II", "DPDPA 2023", "GDPR (for EU clients)", "CERT-In Directions 2022"],
    faqs: [
      { q: "We keep failing enterprise client security questionnaires. Can you help?", a: "Yes. This is a common challenge for Indian IT companies. We audit your current controls against the questionnaire requirements, implement gaps, and produce the evidence documentation that enterprise clients need." },
      { q: "How long does ISO 27001 take for a mid-sized IT company?", a: "Typically 3–5 months for first-time implementation. We provide a realistic project plan after the initial gap assessment." },
    ],
    stats: [{ value: "ISO 27001", label: "Enterprise Client Gateway" }, { value: "SOC 2", label: "Global Trust Signal" }, { value: "Cloud", label: "Security Specialization" }, { value: "SaaS", label: "Platform Security" }],
  },
  {
    slug: "energy",
    title: "Energy & Utilities",
    shortDesc: "OT/IT cybersecurity for power utilities, oil & gas and critical infrastructure — IEC 62443 aligned.",
    iconName: "FiZap",
    gradient: "from-[#F59E0B] to-[#7C3AED]",
    accentColor: "#F59E0B",
    heroDesc: "Energy and utility infrastructure is among the most attractive targets for state-sponsored cyber actors. Power grids, water treatment plants and oil pipelines face persistent threats from nation-state APTs and ransomware groups. Cybria Secure provides IEC 62443 aligned OT/IT security assessment with zero disruption to critical operations.",
    threats: [
      "Nation-state APT attacks on power grid infrastructure",
      "Ransomware targeting SCADA and energy management systems",
      "Remote access exploitation of OT systems",
      "Insider threats with physical and digital access",
      "Supply chain attacks on energy management software vendors",
      "DDoS targeting customer billing and energy trading systems",
      "Smart meter and AMI network vulnerabilities",
      "Environmental sensor network tampering",
    ],
    services: [
      { title: "OT / SCADA Security", slug: "ot-scada-security", desc: "Non-intrusive OT security assessment for energy control systems — IEC 62443 aligned." },
      { title: "Network Security Audit", slug: "network-security-audit", desc: "IT/OT network segmentation, remote access security and DMZ review." },
      { title: "Red Team Operations", slug: "red-teaming", desc: "APT simulation targeting energy infrastructure TTPs." },
      { title: "Incident Response", slug: "incident-response", desc: "Rapid response to OT/IT incidents with operational continuity priority." },
    ],
    regulations: ["IEC 62443", "CERT-In Directions 2022", "CEA Guidelines for Cybersecurity", "ISO 27001"],
    faqs: [
      { q: "Can you test our SCADA system without affecting power supply?", a: "Yes. Our OT assessment methodology is non-intrusive — passive discovery and architecture review for live systems. Active testing is restricted to isolated test environments or IT systems only." },
    ],
    stats: [{ value: "IEC 62443", label: "OT Security Standard" }, { value: "Zero", label: "Operational Disruption" }, { value: "APT", label: "Threat Simulation" }, { value: "24/7", label: "Incident Response" }],
  },
  {
    slug: "telecom",
    title: "Telecom",
    shortDesc: "Network security, API protection and subscriber data security for telecom operators and communication service providers.",
    iconName: "FiPhone",
    gradient: "from-[#10B981] to-[#2B7BE4]",
    accentColor: "#10B981",
    heroDesc: "Telecom operators manage the communication backbone of India — subscriber data, call records, network infrastructure and financial transactions. SS7 vulnerabilities, API attacks on BSS/OSS systems and insider threats make telecom security uniquely complex. Cybria Secure provides specialized security assessment for telecom environments.",
    threats: [
      "SS7 and Diameter protocol vulnerabilities",
      "BSS/OSS API security weaknesses",
      "Subscriber data theft and SIM swap fraud",
      "Ransomware targeting billing and network management systems",
      "Insider threats with network-wide access",
      "DDoS targeting communication infrastructure",
      "VoIP and signaling network exploitation",
      "MVNO partner access exploitation",
    ],
    services: [
      { title: "Network Security Audit", slug: "network-security-audit", desc: "Telecom network infrastructure, interconnect and API security assessment." },
      { title: "API Security Testing", slug: "api-security-testing", desc: "BSS/OSS API, partner API and subscriber management API security testing." },
      { title: "GRC & Risk Assessment", slug: "governance-risk-assessment", desc: "DoT and TRAI cybersecurity compliance framework and risk governance." },
      { title: "Incident Response", slug: "incident-response", desc: "24/7 incident response for telecom operators with network continuity priority." },
    ],
    regulations: ["DoT Security Regulations", "TRAI Regulations", "CERT-In Directions 2022", "ISO 27001", "DPDPA 2023"],
    faqs: [
      { q: "Do you assess SS7 and signaling network security?", a: "Yes. We assess SS7, Diameter and SIP signaling protocol security risks and provide recommendations aligned with GSMA security guidelines." },
    ],
    stats: [{ value: "SS7", label: "Signaling Security" }, { value: "BSS/OSS", label: "System Security Testing" }, { value: "DoT", label: "Regulatory Alignment" }, { value: "24/7", label: "Incident Response" }],
  },
];

export const getIndustryBySlug = (slug: string) => industries.find((i) => i.slug === slug);