// Central data file for all services — edit here to update everywhere
// Icons imported where used — this file exports plain data + type

export type ServiceCategory = {
  id: string;
  label: string;
  color: string;
};

export type ServiceMethodologyStep = { step: number; title: string; desc: string };
export type ServiceFAQ = { q: string; a: string };
export type ServiceWhyItem = { heading: string; body: string };

export type Service = {
  slug: string;
  title: string;
  shortDesc: string;
  category: string;
  iconName: string; // We'll map icon names to components in the UI layer
  gradient: string;
  accentColor: string;
  glowColor: string;
  keywords: string[];
  heroDesc: string;
  whyItMatters: ServiceWhyItem[];
  whatWeAssess: string[];
  methodology: ServiceMethodologyStep[];
  faqs: ServiceFAQ[];
  features: string[];
  benefits: string[];
};

export const categories: ServiceCategory[] = [
  { id: "vapt",       label: "Security Testing (VAPT)",  color: "#2B7BE4" },
  { id: "advanced",   label: "Advanced Assessment",       color: "#EF4444" },
  { id: "compliance", label: "Compliance & GRC",          color: "#7C3AED" },
  { id: "managed",    label: "Managed Security",          color: "#10B981" },
  { id: "training",   label: "Training & Awareness",      color: "#F59E0B" },
];

export const services: Service[] = [
  // ─── VAPT ──────────────────────────────────────────────────────────────────
  {
    slug: "web-application-vapt",
    title: "Web Application VAPT",
    shortDesc: "OWASP-based manual and automated testing for injection, broken auth, IDOR, business logic and API vulnerabilities.",
    category: "vapt",
    iconName: "FiGlobe",
    gradient: "from-[#2B7BE4] to-[#3B82F6]",
    accentColor: "#2B7BE4",
    glowColor: "rgba(43,123,228,0.3)",
    keywords: ["web application VAPT India", "web app penetration testing India", "OWASP testing", "web security testing India"],
    heroDesc: "Your web application is your most exposed attack surface. Our certified ethical hackers perform deep manual and automated testing — beyond automated scanners — to uncover injection flaws, broken authentication, IDOR, business logic vulnerabilities, and API weaknesses before real attackers do.",
    whyItMatters: [
      { heading: "Web apps are the #1 breach vector", body: "Over 43% of data breaches involve web application vulnerabilities. A single SQL injection or broken authentication flaw can expose your entire customer database." },
      { heading: "Automated scanners miss 40–60% of vulnerabilities", body: "Tools like automated Burp Suite scans and OWASP ZAP miss business logic flaws, auth bypasses and chained attack paths. Manual testing by certified professionals is non-negotiable." },
      { heading: "Compliance mandates it", body: "RBI, PCI-DSS, ISO 27001 and SOC 2 all require regular penetration testing of internet-facing applications. A proper VAPT report is your compliance evidence." },
    ],
    whatWeAssess: [
      "Authentication and session management",
      "OWASP Top 10 (injection, XSS, IDOR, broken access control)",
      "Business logic and workflow flaws",
      "API endpoints (REST, GraphQL, SOAP)",
      "File upload and download controls",
      "Sensitive data exposure and cryptography",
      "Third-party integrations and dependencies",
      "Error handling and information leakage",
    ],
    methodology: [
      { step: 1, title: "Scoping & Recon", desc: "Define target URLs, functionalities and user roles. Passive reconnaissance to map the full attack surface." },
      { step: 2, title: "Automated Scanning", desc: "Authenticated and unauthenticated scans using industry-standard tools as a testing baseline." },
      { step: 3, title: "Manual Testing", desc: "Certified testers manually probe every function — login, search, upload, payment, API calls — for logical and technical flaws automated tools miss." },
      { step: 4, title: "Exploitation", desc: "Controlled exploitation of confirmed vulnerabilities with proof-of-concept screenshots to demonstrate real-world impact." },
      { step: 5, title: "Reporting", desc: "Detailed report with CVSS severity ratings, evidence, remediation steps and RBI/ISO compliance mapping." },
      { step: 6, title: "Re-testing", desc: "Free re-test after fixes to verify all critical and high findings are resolved before sign-off." },
    ],
    faqs: [
      { q: "How long does a web application VAPT take?", a: "Typically 3–7 business days depending on application size and complexity. We provide a timeline estimate after the initial scoping call." },
      { q: "Do you test authenticated functionality?", a: "Yes. We test all authenticated user roles — standard user, admin, privileged roles — to find privilege escalation and IDOR vulnerabilities." },
      { q: "Will testing affect our production environment?", a: "We agree on testing hours and use non-destructive techniques. Most engagements use a staging environment; production testing is done during off-peak hours with every precaution taken." },
      { q: "Is your report accepted by RBI inspectors?", a: "Yes. Our reports include manual testing evidence, severity classification and remediation tracking — meeting RBI Master Directions requirements." },
      { q: "Do you provide remediation support?", a: "Yes. Our team clarifies findings and reviews your fixes before the re-test at no additional cost." },
    ],
    features: ["OWASP Top 10 Testing", "Business Logic Testing", "API Security Testing", "Authentication & Session Testing", "File Upload Testing", "SAST & DAST Combined", "CVSS Severity Ratings", "RBI-Ready Report Format"],
    benefits: ["Uncover vulnerabilities before attackers", "Meet RBI / ISO 27001 compliance", "Protect customer data and brand trust", "Avoid regulatory penalties", "Actionable remediation guidance"],
  },
  {
    slug: "network-security-audit",
    title: "Network Security Audit",
    shortDesc: "Internal and external network penetration testing — firewalls, Active Directory, segmentation, VPN and remote access.",
    category: "vapt",
    iconName: "FiServer",
    gradient: "from-[#2B7BE4] to-[#0EA5E9]",
    accentColor: "#0EA5E9",
    glowColor: "rgba(14,165,233,0.3)",
    keywords: ["network penetration testing India", "network security audit India", "internal network VAPT", "Active Directory security testing"],
    heroDesc: "Your network is the backbone of your business. A misconfigured firewall rule, default credential or unpatched server can give attackers full internal access. Our network security audit combines external perimeter testing with internal network penetration to map every exploitable path.",
    whyItMatters: [
      { heading: "Most breaches start at the network perimeter", body: "Exposed RDP, default router credentials, open management ports — attackers scan the internet continuously. Your external attack surface is under constant pressure." },
      { heading: "Internal networks are rarely tested", body: "Companies focus on perimeter defenses but leave internal networks flat and unmonitored. Once inside, attackers move laterally within hours." },
      { heading: "RBI and ISO 27001 require it", body: "Both frameworks mandate network security assessments. Banks and financial institutions face additional requirements under RBI Master Directions on IT Risk." },
    ],
    whatWeAssess: [
      "External attack surface (open ports, services, CVEs)",
      "Firewall rules and ACL configuration",
      "VPN and remote access security",
      "Network segmentation and VLAN effectiveness",
      "Active Directory configuration and attack paths",
      "Switch and router security configurations",
      "DNS, DHCP and NTP security",
      "Wireless network security",
    ],
    methodology: [
      { step: 1, title: "Scoping", desc: "Define IP ranges, subnets, critical systems and rules of engagement." },
      { step: 2, title: "External Recon", desc: "Passive and active reconnaissance of external-facing infrastructure." },
      { step: 3, title: "Vulnerability Scanning", desc: "Authenticated and unauthenticated scanning of all in-scope systems." },
      { step: 4, title: "Manual Exploitation", desc: "Manual exploitation of discovered vulnerabilities — privilege escalation, lateral movement, AD attacks." },
      { step: 5, title: "Internal Assessment", desc: "Simulate insider threat or post-breach lateral movement from inside the network." },
      { step: 6, title: "Report & Re-test", desc: "Full report with network attack chains, remediation steps and re-test validation." },
    ],
    faqs: [
      { q: "What is the difference between external and internal network VAPT?", a: "External VAPT tests what an attacker can reach from the internet. Internal VAPT simulates what happens after an attacker gains initial access — or tests insider threat scenarios." },
      { q: "Do you test Active Directory?", a: "Yes. AD is a common attack target. We test for misconfigured ACLs, Kerberoasting, Pass-the-Hash, DCSync and other AD attack paths." },
      { q: "How disruptive is the testing?", a: "We avoid destructive techniques. Testing is scheduled during low-traffic windows. We never crash production systems." },
      { q: "Can you test our cloud network?", a: "Yes. Cloud network assessment (AWS VPC, Azure VNet) is available as a separate scope or add-on." },
    ],
    features: ["External Perimeter Testing", "Internal Network Pentest", "Active Directory Assessment", "Firewall Rule Review", "VPN Security Testing", "Network Segmentation Check", "Wireless Network Testing", "Attack Chain Report"],
    benefits: ["Identify exploitable network paths", "Harden perimeter defenses", "Validate segmentation controls", "Meet compliance requirements", "Prevent lateral movement attacks"],
  },
  {
    slug: "mobile-app-security",
    title: "Mobile App Security Testing",
    shortDesc: "iOS and Android security testing — data storage, authentication, API security, SSL pinning and reverse engineering.",
    category: "vapt",
    iconName: "FiSmartphone",
    gradient: "from-[#FF5CA8] to-[#EC4899]",
    accentColor: "#FF5CA8",
    glowColor: "rgba(255,92,168,0.3)",
    keywords: ["mobile app penetration testing India", "Android iOS security testing", "mobile VAPT India", "mobile application security India"],
    heroDesc: "Mobile apps handle sensitive customer data, payment information and authentication credentials — yet are often the least-tested part of an organization's attack surface. Our testing covers static analysis, dynamic testing, API security and reverse engineering for Android and iOS.",
    whyItMatters: [
      { heading: "Mobile is the primary channel for Indian users", body: "With 600M+ smartphone users, your mobile app handles more transactions than your website. A single vulnerability impacts your largest user base." },
      { heading: "Insecure data storage is epidemic", body: "Over 65% of mobile apps store sensitive data insecurely — in plaintext SQLite databases, shared preferences or app logs accessible to other apps." },
      { heading: "RBI and fintech regulations apply", body: "Mobile banking apps must comply with RBI guidelines. Payment apps must meet PCI-DSS. Our reports provide the regulatory evidence needed." },
    ],
    whatWeAssess: [
      "Local data storage (SQLite, SharedPreferences, Keychain)",
      "Authentication and session management",
      "API communication security (SSL/TLS, certificate pinning)",
      "Sensitive data in memory and logs",
      "Reverse engineering resistance and obfuscation",
      "Insecure third-party SDKs",
      "Deep link and intent hijacking (Android)",
      "Clipboard and keyboard data leakage",
    ],
    methodology: [
      { step: 1, title: "Static Analysis (SAST)", desc: "Decompile and analyse app binary, source code, manifest files and embedded secrets." },
      { step: 2, title: "Dynamic Analysis (DAST)", desc: "Runtime testing — intercept API traffic, test authentication, monitor data storage during use." },
      { step: 3, title: "API Testing", desc: "Test all backend API endpoints for OWASP API Top 10 vulnerabilities." },
      { step: 4, title: "Reverse Engineering", desc: "Attempt to extract hardcoded secrets, bypass root/jailbreak detection, reverse-engineer business logic." },
      { step: 5, title: "Report & Re-test", desc: "Detailed findings with PoC, severity ratings, remediation steps and re-test." },
    ],
    faqs: [
      { q: "Do you test both Android and iOS?", a: "Yes. We test both platforms. Pricing is per platform or bundled." },
      { q: "Do you need the source code?", a: "No — we test the compiled app binary (APK/IPA) as a real attacker would. Source code review is available as an add-on." },
      { q: "Can you test our banking or payment app?", a: "Yes. We have experience testing RBI-regulated mobile banking apps and PCI-DSS payment apps." },
    ],
    features: ["Android & iOS Testing", "Static Analysis (SAST)", "Dynamic Analysis (DAST)", "API Security Testing", "SSL Pinning Bypass Testing", "Reverse Engineering", "RBI-Ready Report", "Re-test Included"],
    benefits: ["Protect customer data on mobile", "Meet RBI mobile banking guidelines", "Prevent app reverse engineering", "Secure payment flows", "Uncover backend API vulnerabilities"],
  },
  {
    slug: "cloud-security-assessment",
    title: "Cloud Security Assessment",
    shortDesc: "AWS, Azure and GCP configuration review — IAM, storage exposure, network controls, encryption and compliance posture.",
    category: "vapt",
    iconName: "FiCloud",
    gradient: "from-[#7C3AED] to-[#8B5CF6]",
    accentColor: "#7C3AED",
    glowColor: "rgba(124,58,237,0.3)",
    keywords: ["cloud security assessment India", "AWS security audit India", "Azure security testing India", "cloud VAPT India", "GCP security review"],
    heroDesc: "Cloud misconfigurations — not sophisticated hacking — cause most cloud breaches. A single public S3 bucket, over-permissive IAM role or exposed management console can expose millions of records. Our cloud security assessment finds misconfigurations before attackers do.",
    whyItMatters: [
      { heading: "Misconfiguration causes 99% of cloud breaches", body: "Gartner estimates 99% of cloud security failures are the customer's fault — misconfigured IAM, exposed storage, default security groups. Your cloud provider is not responsible for your configuration." },
      { heading: "Cloud shared responsibility model is widely misunderstood", body: "AWS/Azure/GCP secure their infrastructure. You're responsible for your configuration, data and access controls. Most organizations don't fully understand what they own." },
      { heading: "CERT-In compliance requires cloud security controls", body: "India's CERT-In guidelines and RBI Master Directions for cloud usage require documented cloud security assessment and controls." },
    ],
    whatWeAssess: [
      "IAM policies, roles and over-permissive access",
      "Storage bucket public exposure (S3, Blob, GCS)",
      "Network security groups and firewall rules",
      "Encryption at rest and in transit",
      "Logging, monitoring and alerting configuration",
      "Container and Kubernetes security",
      "Serverless function security",
      "Multi-account and organization-level controls",
    ],
    methodology: [
      { step: 1, title: "Access & Scoping", desc: "Receive read-only access. Define scope — accounts, regions, services in scope." },
      { step: 2, title: "Configuration Review", desc: "Automated and manual review of all configurations against CIS Benchmarks." },
      { step: 3, title: "IAM Analysis", desc: "Deep analysis of identity and access — who has access to what, unused privileges, escalation paths." },
      { step: 4, title: "Network Security", desc: "Review security groups, NACLs, VPC configurations and internet-facing resources." },
      { step: 5, title: "Data Protection", desc: "Assess encryption, key management, backup and data residency controls." },
      { step: 6, title: "Report & Remediation", desc: "Prioritized findings with Terraform/CLI remediation guidance and re-assessment." },
    ],
    faqs: [
      { q: "Which cloud platforms do you support?", a: "AWS, Microsoft Azure and Google Cloud Platform. Multi-cloud environments are supported." },
      { q: "What access do you need?", a: "Read-only access — a SecurityAudit-level IAM role (AWS) or equivalent. We never need production write access." },
      { q: "How is this different from a cloud penetration test?", a: "Configuration review analyses settings and policies. Cloud penetration testing actively exploits misconfigurations. We recommend the review first, then penetration testing." },
    ],
    features: ["AWS / Azure / GCP Support", "IAM Policy Review", "Storage Exposure Detection", "Network Security Review", "Container & Kubernetes", "CIS Benchmark Assessment", "Encryption Review", "Compliance Mapping"],
    benefits: ["Find misconfigurations before attackers", "Reduce cloud attack surface", "Meet CERT-In cloud requirements", "Validate data protection controls", "Prioritized remediation roadmap"],
  },
  {
    slug: "api-security-testing",
    title: "API Security Testing",
    shortDesc: "REST, GraphQL and SOAP API testing against OWASP API Top 10 — BOLA, broken auth, injection, rate limiting and data exposure.",
    category: "vapt",
    iconName: "FiCode",
    gradient: "from-[#2B7BE4] to-[#7C3AED]",
    accentColor: "#5B6EF7",
    glowColor: "rgba(91,110,247,0.3)",
    keywords: ["API security testing India", "REST API penetration testing India", "GraphQL security testing", "API VAPT India", "OWASP API Top 10"],
    heroDesc: "APIs are the primary attack target in modern applications. Broken object-level authorization (BOLA), mass assignment, and absent rate limiting have caused some of the largest data breaches of recent years. We test every API endpoint your application exposes.",
    whyItMatters: [
      { heading: "APIs expose your entire data layer", body: "Unlike web pages, APIs return raw data. A single broken authorization check can expose every user's records, not just the current user's." },
      { heading: "OWASP API Top 10 vulnerabilities are widely exploited", body: "BOLA, broken authentication, excessive data exposure — these are behind real breaches, not theoretical attacks." },
      { heading: "Microservices expand the attack surface", body: "Dozens of microservices mean dozens of API attack surfaces, often with inconsistent security controls between teams." },
    ],
    whatWeAssess: [
      "Broken Object Level Authorization (BOLA/IDOR)",
      "Broken authentication and session tokens",
      "Excessive data exposure in API responses",
      "Lack of rate limiting and resource throttling",
      "Mass assignment vulnerabilities",
      "Security misconfigurations in API gateways",
      "Injection vulnerabilities across all input fields",
      "Undocumented and shadow API endpoints",
    ],
    methodology: [
      { step: 1, title: "API Discovery", desc: "Map all endpoints — documented and undocumented — from traffic interception and documentation review." },
      { step: 2, title: "Authentication Testing", desc: "Test token generation, storage, expiry and bypass possibilities." },
      { step: 3, title: "Authorization Testing", desc: "BOLA/IDOR testing by manipulating object identifiers across user accounts and roles." },
      { step: 4, title: "Input Validation", desc: "Fuzz all input parameters for injection, format string and type confusion vulnerabilities." },
      { step: 5, title: "Business Logic", desc: "Test API workflows for logic flaws — price manipulation, workflow bypass, privilege escalation." },
      { step: 6, title: "Report & Re-test", desc: "OWASP API Top 10 mapped report with severity, PoC and fix guidance." },
    ],
    faqs: [
      { q: "Do you test GraphQL APIs?", a: "Yes. GraphQL has specific risks — introspection exposure, field-level authorization issues, query depth attacks. We test all of these." },
      { q: "What do you need to start?", a: "API documentation (Swagger/Postman collection) if available, test credentials for each user role, and the API base URL. We can work without documentation." },
      { q: "Can you test internal microservices APIs?", a: "Yes. Internal API testing requires VPN or on-site access. We test service-to-service communication as well." },
    ],
    features: ["OWASP API Top 10", "REST / GraphQL / SOAP", "BOLA / IDOR Testing", "Rate Limit Bypass Testing", "Mass Assignment Testing", "Auth Token Analysis", "Business Logic Testing", "Postman Report Delivery"],
    benefits: ["Prevent unauthorized data access", "Fix authorization vulnerabilities", "Protect customer PII in responses", "Meet security compliance", "Evidence for auditors"],
  },
  {
    slug: "ot-scada-security",
    title: "OT / SCADA Security",
    shortDesc: "Non-intrusive security assessment for industrial control systems, SCADA, PLCs and OT/IT convergence environments.",
    category: "vapt",
    iconName: "FiCpu",
    gradient: "from-[#F59E0B] to-[#EF4444]",
    accentColor: "#F59E0B",
    glowColor: "rgba(245,158,11,0.3)",
    keywords: ["OT security India", "SCADA security assessment India", "ICS security testing India", "OT VAPT India", "industrial cybersecurity"],
    heroDesc: "Operational Technology environments — SCADA, PLCs, DCS and industrial networks — were never designed for cybersecurity. As OT connects to corporate IT for remote monitoring, the attack surface grows dramatically. We perform non-intrusive OT security assessments that protect critical operations without disrupting production.",
    whyItMatters: [
      { heading: "OT attacks cause physical damage and production shutdown", body: "Unlike IT breaches that compromise data, OT attacks halt production lines, damage equipment and create safety hazards. Indian manufacturing is an active target." },
      { heading: "OT/IT convergence creates new attack paths", body: "Connecting SCADA to corporate networks creates lateral movement paths. Attackers that breach your email server can reach your PLC." },
      { heading: "IEC 62443 compliance is becoming mandatory", body: "Critical infrastructure operators and their vendors are increasingly required to demonstrate OT security against IEC 62443 and CERT-In guidelines." },
    ],
    whatWeAssess: [
      "OT/IT network segmentation and DMZ design",
      "SCADA/HMI access controls and authentication",
      "PLC and RTU firmware and default credentials",
      "Remote access to OT systems (RDP, VNC)",
      "Industrial protocol security (Modbus, DNP3, OPC-UA)",
      "Historian server exposure",
      "Engineering workstation security",
      "Vendor remote access controls",
    ],
    methodology: [
      { step: 1, title: "Passive Discovery", desc: "Non-intrusive asset discovery — identify all OT devices without active probes that could disrupt PLCs." },
      { step: 2, title: "Architecture Review", desc: "Review network diagrams, segmentation design and OT/IT connection points." },
      { step: 3, title: "Configuration Review", desc: "Review SCADA configurations, historian settings, HMI access controls." },
      { step: 4, title: "IT Network VAPT", desc: "Active penetration testing of IT network to find paths into OT environment." },
      { step: 5, title: "Risk Assessment", desc: "OT-specific risk assessment aligned with IEC 62443 and CERT-In guidelines." },
      { step: 6, title: "Remediation Roadmap", desc: "Prioritized plan with OT-specific constraints — maintenance windows, vendor dependencies." },
    ],
    faqs: [
      { q: "Will the assessment disrupt production?", a: "No. We use passive, non-intrusive techniques for all OT systems. Active testing is only on IT systems and requires explicit approval. We never probe PLCs or RTUs actively." },
      { q: "Our OT vendor says their systems are secure. Do we still need assessment?", a: "OT vendors secure their product, not your deployment. Default credentials, flat networks and unpatched systems are configuration issues — independent assessment is essential." },
      { q: "Can you help design OT/IT segmentation?", a: "Yes. Remediation support includes network segmentation design recommendations and architecture review." },
    ],
    features: ["Non-Intrusive OT Testing", "SCADA / HMI Assessment", "PLC Security Review", "OT/IT Segmentation Check", "IEC 62443 Alignment", "Industrial Protocol Analysis", "Remote Access Review", "Production-Safe Methodology"],
    benefits: ["Protect production continuity", "Identify OT/IT convergence risks", "Meet IEC 62443 requirements", "Prevent ransomware reaching OT", "Vendor-independent assessment"],
  },
  // ─── ADVANCED ──────────────────────────────────────────────────────────────
  {
    slug: "red-teaming",
    title: "Red Team Operations",
    shortDesc: "Full-scope adversarial simulation across digital, physical and social engineering vectors to test real-world detection and response.",
    category: "advanced",
    iconName: "FiTarget",
    gradient: "from-[#EF4444] to-[#B91C1C]",
    accentColor: "#EF4444",
    glowColor: "rgba(239,68,68,0.3)",
    keywords: ["red team India", "red teaming services India", "adversarial simulation India", "APT simulation India", "red team operations India"],
    heroDesc: "A penetration test finds vulnerabilities. A red team operation answers the harder question: can your team detect and respond to a real attack? We simulate advanced threat actor TTPs across digital, physical and human vectors simultaneously — testing your entire security posture under realistic conditions.",
    whyItMatters: [
      { heading: "Passing a VAPT doesn't mean you can detect an attack", body: "VAPT finds vulnerabilities. Red teaming tests whether your SOC, SIEM and incident response team actually detect and stop an attacker using those vulnerabilities — stealthily, over weeks." },
      { heading: "Advanced attackers chain multiple low-severity findings", body: "A misconfigured email server + a phishing-susceptible employee + an over-permissive AD account = full domain compromise. Red teaming finds these multi-step chains." },
      { heading: "Advanced compliance frameworks require it", body: "TIBER-EU, RBI's advanced security frameworks and ISO 27001 maturity requirements push organizations toward adversarial testing beyond basic VAPT." },
    ],
    whatWeAssess: [
      "External initial access (phishing, vulnerable services, supply chain)",
      "Physical security (tailgating, access badge cloning, device drops)",
      "Social engineering (pretexting, vishing, impersonation)",
      "Lateral movement and privilege escalation",
      "Active Directory and identity attacks",
      "Data exfiltration techniques and evidence",
      "Detection and response capability of SOC",
      "EDR, SIEM and email security evasion",
    ],
    methodology: [
      { step: 1, title: "Planning & Intelligence", desc: "Define objectives and rules of engagement. OSINT on target — employees, infrastructure, supply chain." },
      { step: 2, title: "Initial Access", desc: "Gain entry via phishing, vulnerable external services, physical access or supply chain — whichever succeeds." },
      { step: 3, title: "Persistence", desc: "Establish persistent access using techniques that evade detection — living off the land, signed binaries." },
      { step: 4, title: "Lateral Movement", desc: "Move through the network toward defined objectives — domain controller, finance systems, customer data." },
      { step: 5, title: "Objective Achievement", desc: "Reach defined objectives — data exfiltration, ransomware simulation, access to crown jewels." },
      { step: 6, title: "Purple Team Debrief", desc: "Joint debrief with your security team — walkthrough of every technique, detection gaps and improvement plan." },
    ],
    faqs: [
      { q: "What's the difference between red teaming and VAPT?", a: "VAPT finds all vulnerabilities in a defined scope. Red teaming is goal-oriented — simulate a real attacker achieving a specific objective using any means necessary, while your team tries to detect it." },
      { q: "How long does a red team engagement take?", a: "Typically 4–8 weeks. Shorter engagements miss the stealth and persistence aspects that make red teaming valuable." },
      { q: "Who in our organisation knows about the engagement?", a: "Only 2–3 executives (the 'white cell'). The SOC is kept unaware — this is essential to test real detection capability." },
      { q: "What is a purple team exercise?", a: "Red and blue teams work together — red team shows techniques, blue team tunes detections in real time. We offer both red team and purple team engagements." },
    ],
    features: ["Full-Scope Adversarial Simulation", "Physical Security Testing", "Social Engineering", "APT TTP Emulation", "MITRE ATT&CK Mapping", "Detection & Response Testing", "Purple Team Option", "Executive Debrief"],
    benefits: ["Test real detection capability", "Find multi-step attack chains", "Improve SOC effectiveness", "Validate security investments", "Meet advanced compliance requirements"],
  },
  {
    slug: "incident-response",
    title: "Incident Response",
    shortDesc: "24/7 rapid response to contain, investigate and recover from ransomware, data breaches and insider threats.",
    category: "advanced",
    iconName: "FiAlertTriangle",
    gradient: "from-[#FF5CA8] to-[#7C3AED]",
    accentColor: "#FF5CA8",
    glowColor: "rgba(255,92,168,0.3)",
    keywords: ["incident response India", "cyber incident response India", "ransomware response India", "breach response India", "DFIR India"],
    heroDesc: "When a breach happens, every minute counts. Our 24/7 incident response team contains the threat, preserves forensic evidence, recovers your systems, and files mandatory RBI/CERT-In notifications — all while keeping your business running.",
    whyItMatters: [
      { heading: "Average breach detection time in India is 230 days", body: "Most organisations don't discover breaches for months. By then, attackers have established persistence, moved laterally, and exfiltrated data. Rapid response limits the damage window dramatically." },
      { heading: "RBI requires notification within 6 hours", body: "Banks and financial institutions must notify RBI of cyber incidents within 6 hours of detection. Missing this deadline attracts regulatory action on top of the breach itself." },
      { heading: "Ransomware without an IR plan costs 10x more", body: "Organisations with tested incident response plans recover from ransomware in days. Those without IR plans take weeks and often pay the ransom." },
    ],
    whatWeAssess: [
      "Scope and extent of compromise",
      "Attack entry point and initial access vector",
      "Lateral movement paths taken by attacker",
      "Data exfiltration evidence and volume",
      "Malware families and persistence mechanisms",
      "Affected systems and data classification",
      "RBI/CERT-In notification requirements",
      "Recovery readiness — backup integrity and rebuild capacity",
    ],
    methodology: [
      { step: 1, title: "Triage & Containment", desc: "Immediately isolate affected systems to stop lateral spread. Preserve forensic state before cleanup." },
      { step: 2, title: "Forensic Investigation", desc: "Disk, memory and network forensics to determine what happened, when, how and what was accessed." },
      { step: 3, title: "Regulatory Notification", desc: "Draft and file RBI/CERT-In/SEBI incident notifications within required timeframes." },
      { step: 4, title: "Eradication", desc: "Remove attacker persistence, clean infected systems, rebuild from known-good state." },
      { step: 5, title: "Recovery", desc: "Restore operations from clean backups, validate data integrity, monitor for re-infection." },
      { step: 6, title: "Post-Incident Review", desc: "Root cause analysis, lessons learned report, IRP improvement and hardening recommendations." },
    ],
    faqs: [
      { q: "How quickly can you respond?", a: "We are available 24/7. Remote response begins within 2 hours of engagement. On-site response in Kolhapur and surroundings within 4 hours." },
      { q: "We've been hit by ransomware. Should we pay?", a: "We advise against paying ransom unless there is absolutely no recovery path. Contact us immediately — we'll assess your backup situation and options before any decision is made." },
      { q: "Can you help us file the RBI cyber incident notification?", a: "Yes. We draft and review the mandatory RBI notification as part of every banking sector engagement. Meeting the 6-hour deadline is a priority." },
      { q: "Do you offer IR retainer services?", a: "Yes. Our IR retainer provides priority response SLAs, pre-authorised access and pre-positioned forensic tools for faster response when it matters most." },
    ],
    features: ["24/7 Response Availability", "Digital Forensics (DFIR)", "Ransomware Recovery", "RBI Notification Support", "Malware Analysis", "Forensic Evidence Preservation", "Recovery Planning", "Post-Incident Hardening"],
    benefits: ["Contain breaches faster", "Meet RBI 6-hour notification SLA", "Minimize data loss and downtime", "Preserve forensic evidence", "Prevent recurrence with root cause fix"],
  },
  // ─── COMPLIANCE ─────────────────────────────────────────────────────────────
  {
    slug: "rbi-compliance",
    title: "RBI Cybersecurity Compliance",
    shortDesc: "End-to-end RBI cybersecurity framework compliance for cooperative banks, UCBs, NBFCs and payment system operators.",
    category: "compliance",
    iconName: "FiClipboard",
    gradient: "from-[#7C3AED] to-[#2B7BE4]",
    accentColor: "#7C3AED",
    glowColor: "rgba(124,58,237,0.3)",
    keywords: ["RBI cybersecurity compliance India", "RBI IT framework", "cooperative bank cybersecurity", "NBFC compliance India", "RBI Master Directions"],
    heroDesc: "RBI's Master Directions on IT Governance, Risk, Controls and Assurance set stringent cybersecurity requirements for every regulated entity. Non-compliance isn't just a fine — it's an existential risk. We help banks, cooperative banks, UCBs and NBFCs achieve and maintain full RBI compliance.",
    whyItMatters: [
      { heading: "RBI is actively penalising non-compliant banks", body: "RBI has imposed penalties on multiple cooperative banks for cybersecurity non-compliance in the past 24 months. The enforcement posture has hardened significantly." },
      { heading: "6-hour incident notification is now law", body: "Missing the mandatory 6-hour cyber incident reporting window is a compliance breach on top of the incident. Most banks don't have a tested IRP to meet this deadline." },
      { heading: "Annual VAPT is mandatory", body: "RBI mandates annual VAPT for internet-facing systems, quarterly for critical ones. Many cooperative banks still don't have a single VAPT report on file." },
    ],
    whatWeAssess: [
      "IT Governance structure (Board policy, CISO mandate)",
      "Cybersecurity Policy completeness and Board approval status",
      "Annual VAPT compliance documentation",
      "Incident Response Plan existence and test evidence",
      "Business Continuity Plan and DR test results",
      "Vendor and third-party risk management controls",
      "Patch management and vulnerability management process",
      "User access management and privileged access controls",
    ],
    methodology: [
      { step: 1, title: "Gap Assessment", desc: "Benchmark current state against all RBI Master Direction requirements. Prioritized gap report." },
      { step: 2, title: "Policy & Governance", desc: "Draft or update Cybersecurity Policy, IT Risk Framework and IRP — ready for Board approval." },
      { step: 3, title: "Technical Controls", desc: "Implement or harden network segmentation, MFA, endpoint protection and log management." },
      { step: 4, title: "VAPT", desc: "Conduct annual VAPT with RBI-format report — manual testing evidence included." },
      { step: 5, title: "Training & Drills", desc: "Staff awareness training, Board cyber briefing, IRP tabletop exercise with evidence." },
      { step: 6, title: "Ongoing Compliance", desc: "Quarterly review, pre-inspection preparation, continuous monitoring support." },
    ],
    faqs: [
      { q: "What does RBI require for cooperative banks?", a: "Board-approved Cybersecurity Policy, CISO appointment, annual VAPT, tested IRP, BCP/DR with verified RTO/RPO, and periodic security awareness training for all staff." },
      { q: "We have an upcoming RBI inspection. Can you help prepare?", a: "Yes. Our pre-inspection preparation includes gap assessment, document review, evidence compilation and mock inspection walkthrough. Contact us immediately — preparation time matters." },
      { q: "Do you provide CISO-as-a-Service?", a: "Yes. For cooperative banks and NBFCs without a full-time CISO, our vCISO service fulfills the RBI compliance mandate at a fraction of the cost." },
    ],
    features: ["RBI Gap Assessment", "Policy & Governance Documentation", "VAPT with RBI-Format Report", "IRP Development & Testing", "BCP/DR Assessment", "CISO-as-a-Service", "Staff Training Evidence", "Pre-Inspection Preparation"],
    benefits: ["Pass RBI inspections confidently", "Avoid regulatory penalties", "Meet all Master Direction requirements", "File incident notifications on time", "Board-ready compliance documentation"],
  },
  {
    slug: "iso-27001",
    title: "ISO 27001 Implementation",
    shortDesc: "End-to-end ISO 27001:2022 ISMS implementation, gap assessment, certification readiness and audit support.",
    category: "compliance",
    iconName: "FiShield",
    gradient: "from-[#10B981] to-[#059669]",
    accentColor: "#10B981",
    glowColor: "rgba(16,185,129,0.3)",
    keywords: ["ISO 27001 India", "ISO 27001 implementation India", "ISMS certification India", "ISO 27001 consultant India", "ISO 27001:2022"],
    heroDesc: "ISO 27001:2022 is the global gold standard for information security management. Enterprise clients and MNCs now mandate it from vendors. We guide you from gap assessment to certification — with an ISMS that actually works, not just a paper exercise.",
    whyItMatters: [
      { heading: "Enterprise clients require ISO 27001", body: "Large Indian enterprises and MNCs increasingly mandate ISO 27001 from their technology vendors. Without it, you're excluded from enterprise RFPs and contracts." },
      { heading: "2022 version added 11 new controls", body: "ISO 27001:2022 introduced significant new controls — cloud security, threat intelligence, data masking, secure coding. Many certified organisations need re-assessment." },
      { heading: "Globally recognised security signal", body: "For Indian companies pursuing international clients, ISO 27001 opens doors in Europe, Middle East and North America." },
    ],
    whatWeAssess: [
      "ISMS maturity against ISO 27001:2022 Annex A controls",
      "Asset inventory and information classification",
      "Risk assessment methodology and treatment",
      "Security controls implementation and effectiveness",
      "Supplier and third-party security requirements",
      "Incident management and evidence",
      "Business continuity and disaster recovery",
      "Internal audit program and management review cadence",
    ],
    methodology: [
      { step: 1, title: "Gap Assessment", desc: "Benchmark against all ISO 27001:2022 clauses and Annex A controls with effort estimates." },
      { step: 2, title: "Risk Assessment", desc: "Asset-based risk assessment using ISO 27005 methodology. Risk register and treatment plan." },
      { step: 3, title: "ISMS Documentation", desc: "Develop all required policies, procedures, SoA, risk treatment plan and records." },
      { step: 4, title: "Controls Implementation", desc: "Support implementation of technical and organisational controls from Annex A." },
      { step: 5, title: "Internal Audit", desc: "Conduct internal audit to identify non-conformities before the certification audit." },
      { step: 6, title: "Certification Support", desc: "Support during Stage 1 and Stage 2 audits. Address non-conformities to achieve certification." },
    ],
    faqs: [
      { q: "How long does ISO 27001 certification take?", a: "Typically 3–6 months for first-time implementation depending on organization size and current maturity. We provide a project plan after the gap assessment." },
      { q: "Do you help select the certification body?", a: "Yes. We work with multiple accredited certification bodies and recommend the right one for your size, industry and budget." },
      { q: "We need to transition to ISO 27001:2022. Can you help?", a: "Yes. We provide a transition gap assessment and support updating your ISMS and SoA for the 2022 version." },
    ],
    features: ["Gap Assessment", "Risk Assessment (ISO 27005)", "Full ISMS Documentation", "Annex A Controls Implementation", "Internal Audit", "Certification Body Liaison", "2022 Version Transition", "Ongoing ISMS Support"],
    benefits: ["Win enterprise and international clients", "Demonstrate security maturity globally", "Structured risk management framework", "Simplify RBI compliance", "Globally recognised certification"],
  },
  {
    slug: "governance-risk-assessment",
    title: "Governance, Risk & Compliance (GRC)",
    shortDesc: "Cybersecurity risk assessment, GRC framework, third-party risk management, DPDPA compliance and security policy development.",
    category: "compliance",
    iconName: "FiBarChart2",
    gradient: "from-[#FF5CA8] to-[#EC4899]",
    accentColor: "#FF5CA8",
    glowColor: "rgba(255,92,168,0.3)",
    keywords: ["GRC framework India", "cybersecurity risk assessment India", "governance risk compliance India", "DPDPA compliance India", "third party risk management"],
    heroDesc: "Cybersecurity without governance is just tools and hope. Our GRC services build the strategic framework that turns security from a cost centre into a business enabler — aligning risk management with your business objectives and giving leadership the visibility they need.",
    whyItMatters: [
      { heading: "What gets measured gets managed", body: "Without a formal risk assessment, security teams react to incidents rather than prevent them. A GRC framework gives you a structured, prioritized view of your risk landscape." },
      { heading: "Regulators want governance, not just controls", body: "RBI, SEBI and CERT-In inspections check whether management and the Board are engaged with cybersecurity governance — not just whether a firewall exists." },
      { heading: "Third-party risk is your biggest blind spot", body: "Your CBS vendor, payroll system, payment gateway — each is an attack path into your organisation. Third-party risk management closes this gap." },
    ],
    whatWeAssess: [
      "IT Risk Assessment against your asset inventory",
      "Threat landscape relevant to your industry",
      "Existing security controls effectiveness",
      "Regulatory compliance gaps (RBI, SEBI, CERT-In, DPDPA)",
      "Third-party and vendor security posture",
      "Security policy completeness",
      "Board and management security governance",
      "Business continuity and risk appetite alignment",
    ],
    methodology: [
      { step: 1, title: "Risk Identification", desc: "Asset inventory, threat modelling and vulnerability identification across people, process and technology." },
      { step: 2, title: "Risk Analysis", desc: "Qualitative and quantitative risk analysis — likelihood, impact and composite risk scoring." },
      { step: 3, title: "Risk Evaluation", desc: "Risk register with prioritization against your defined risk appetite." },
      { step: 4, title: "Risk Treatment", desc: "Risk treatment plans — accept, mitigate, transfer or avoid for each identified risk." },
      { step: 5, title: "Policy & Framework", desc: "Develop or update security policies, procedures and governance frameworks." },
      { step: 6, title: "Monitoring & Reporting", desc: "Ongoing risk monitoring, KRI dashboards and Board-ready reporting cadence." },
    ],
    faqs: [
      { q: "What is the difference between GRC and VAPT?", a: "VAPT is a technical assessment that finds vulnerabilities. GRC is a strategic framework that identifies, prioritizes and manages all business risks — including but not limited to technical ones. Both are needed." },
      { q: "Do you help with DPDPA compliance?", a: "Yes. India's Digital Personal Data Protection Act 2023 (DPDPA) is a key new requirement. We assess current data processing practices against DPDPA and build the compliance roadmap." },
      { q: "How long does a risk assessment take?", a: "A comprehensive IT risk assessment for a mid-sized organization typically takes 2–3 weeks. Output is a risk register, risk treatment plan and Board-ready summary." },
    ],
    features: ["IT Risk Assessment", "Risk Register Development", "GRC Framework Implementation", "Third-Party Risk Management", "DPDPA Compliance", "Security Policy Development", "Board Risk Reporting", "Continuous Risk Monitoring"],
    benefits: ["Board-level risk visibility", "Structured risk management", "Regulatory compliance confidence", "Vendor risk under control", "Proactive vs reactive security"],
  },
  // ─── MANAGED ────────────────────────────────────────────────────────────────
  {
    slug: "vciso",
    title: "Virtual CISO (vCISO)",
    shortDesc: "Fractional CISO service — strategic security leadership, Board reporting and compliance management without the full-time cost.",
    category: "managed",
    iconName: "FiUsers",
    gradient: "from-[#10B981] to-[#0EA5E9]",
    accentColor: "#10B981",
    glowColor: "rgba(16,185,129,0.3)",
    keywords: ["virtual CISO India", "vCISO India", "fractional CISO India", "CISO as a service India", "cybersecurity leadership India"],
    heroDesc: "A full-time CISO costs ₹50–80L per annum. Most Indian SMEs, cooperative banks and growing companies need security leadership for compliance, Board reporting and vendor oversight — but can't justify a full-time executive. Our vCISO delivers that leadership at a fraction of the cost.",
    whyItMatters: [
      { heading: "RBI mandates CISO appointment", body: "RBI's Master Directions require all regulated entities to appoint a CISO with defined reporting lines. For smaller banks and NBFCs, a vCISO fulfills this requirement without the full-time cost." },
      { heading: "Boards need security leadership, not just reports", body: "A vCISO translates technical risk into business language that Board members understand — and takes accountability for the security program." },
      { heading: "Security strategy requires dedicated leadership", body: "Without a CISO, security decisions are reactive, budgets are underfunded and compliance gaps accumulate. A vCISO builds a proactive, strategic program." },
    ],
    whatWeAssess: [
      "Current security posture and maturity level",
      "Compliance obligations and gap status",
      "Security team capability and structure",
      "Vendor and third-party risk landscape",
      "Budget allocation and ROI",
      "Board risk appetite and reporting needs",
      "Incident response readiness",
      "Security roadmap against business objectives",
    ],
    methodology: [
      { step: 1, title: "Onboarding & Assessment", desc: "Understand your business, compliance obligations, current security state and key stakeholders." },
      { step: 2, title: "Strategy Development", desc: "Build 12-month security roadmap aligned with business objectives, budget and compliance requirements." },
      { step: 3, title: "Ongoing Leadership", desc: "Regular engagement — Board presentations, vendor assessments, policy oversight, team mentoring." },
      { step: 4, title: "Compliance Management", desc: "Own the compliance calendar — VAPT scheduling, audit preparation, policy reviews, certifications." },
      { step: 5, title: "Incident Support", desc: "On-call during incidents — decision support, regulatory communication, stakeholder management." },
      { step: 6, title: "Reporting & Review", desc: "Quarterly security scorecards, risk register updates and Board-ready reporting." },
    ],
    faqs: [
      { q: "How many days per month is a vCISO engaged?", a: "Typically 4–8 days per month depending on your organization's size and needs. We customize engagement models to fit your requirements." },
      { q: "Can a vCISO fulfill RBI's CISO mandate?", a: "Yes, for most cooperative banks and NBFCs. The RBI mandate requires CISO functions to be fulfilled — it does not require a full-time employee in most cases. We clarify this for your specific licence type." },
      { q: "Do you provide Board presentations?", a: "Yes. Quarterly Board presentations on cybersecurity posture, risk status and program progress are a standard deliverable." },
    ],
    features: ["Strategic Security Roadmap", "Board & Management Reporting", "Compliance Calendar Management", "Vendor Risk Oversight", "Incident Decision Support", "Security Policy Ownership", "Team Mentoring", "RBI CISO Mandate Fulfillment"],
    benefits: ["CISO capability at SME cost", "Board-level security accountability", "Fulfill RBI CISO requirement", "Proactive security program", "Expert on-call during incidents"],
  },
  // ─── TRAINING ───────────────────────────────────────────────────────────────
  {
    slug: "security-awareness-training",
    title: "Security Awareness Training",
    shortDesc: "Customised employee security training, phishing simulations and awareness campaigns — available in English, Hindi and Marathi.",
    category: "training",
    iconName: "FiBookOpen",
    gradient: "from-[#F59E0B] to-[#EF4444]",
    accentColor: "#F59E0B",
    glowColor: "rgba(245,158,11,0.3)",
    keywords: ["security awareness training India", "employee cybersecurity training India", "phishing simulation India", "cybersecurity training Marathi", "RBI training compliance"],
    heroDesc: "95% of successful cyberattacks involve human error. Technical controls don't protect against an employee clicking a phishing link or sharing credentials over the phone. Our training transforms employees from your weakest link into a human firewall — in the languages they actually work in.",
    whyItMatters: [
      { heading: "Phishing is the #1 initial access vector", body: "Over 90% of ransomware attacks begin with a phishing email. A trained employee who doesn't click is your most effective and cheapest defence." },
      { heading: "RBI mandates annual security awareness training", body: "RBI Master Directions require periodic security awareness training for all staff with documented evidence available for inspection." },
      { heading: "Local language training delivers 3x better retention", body: "English-only training is ineffective for branch staff in Tier 2 cities. Our Marathi and Hindi programs achieve dramatically better knowledge retention in local cooperative bank branches." },
    ],
    whatWeAssess: [
      "Current phishing susceptibility baseline",
      "Staff awareness of social engineering techniques",
      "Password hygiene and policy adherence",
      "Security incident reporting culture",
      "Executive and privileged user awareness gaps",
      "Training content relevance to actual job roles",
      "Post-training knowledge retention",
      "Behavioral change over repeated simulations",
    ],
    methodology: [
      { step: 1, title: "Baseline Phishing Test", desc: "Simulated phishing campaign to measure current susceptibility before any training." },
      { step: 2, title: "Role-Based Training", desc: "Customised modules by role — branch staff, IT team, executives, finance, HR." },
      { step: 3, title: "Awareness Campaigns", desc: "Posters, screensavers, email tips and intranet content in English, Hindi and Marathi." },
      { step: 4, title: "Phishing Simulations", desc: "Ongoing simulations with immediate micro-training for those who click — not punishment." },
      { step: 5, title: "Knowledge Assessment", desc: "Post-training quizzes and assessments to measure knowledge gain." },
      { step: 6, title: "Evidence & Reporting", desc: "Completion certificates, attendance records and RBI-format evidence reports." },
    ],
    faqs: [
      { q: "Do you provide training in Marathi?", a: "Yes. Marathi-language training is particularly effective for cooperative bank branch staff in Kolhapur, Sangli, Ichalkaranji and Western Maharashtra." },
      { q: "How often should phishing simulations run?", a: "Monthly simulations produce the best behavioral change. Quarterly is the minimum for RBI compliance evidence." },
      { q: "Can you train our Board separately?", a: "Yes. We run a separate Board-level session covering cyber risk governance, fiduciary responsibilities and what to ask management about security." },
      { q: "Do certificates work as RBI compliance evidence?", a: "Yes. Every participant receives a completion certificate. We provide aggregate training reports in a format suitable for RBI inspection documentation." },
    ],
    features: ["English, Hindi & Marathi Content", "Role-Based Training", "Phishing Simulations", "Board-Level Sessions", "Knowledge Assessments", "RBI Compliance Evidence", "Awareness Poster Pack", "Behavioral Metrics Reporting"],
    benefits: ["Reduce phishing susceptibility", "Meet RBI training requirements", "Build security-conscious culture", "Protect against social engineering", "RBI inspection-ready documentation"],
  },
];

export const getServiceBySlug = (slug: string): Service | undefined =>
  services.find((s) => s.slug === slug);

export const getServicesByCategory = (categoryId: string): Service[] =>
  services.filter((s) => s.category === categoryId);